# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'Red'), (1, 'Blue'), (2, 'Green'), (3, 'Purple')], max_length=20)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='teams.Team')),
            ],
        ),
    ]
